## Assignment No.2

# Section A

In [1]:
#Q1.List Operations

my_list = [10, 20, 30, 40, 50]

my_list.append(60)
print("After append:", my_list)

my_list.extend([70, 80])
print("After extend:", my_list)

my_list.insert(2, 25)
print("After insert:", my_list)

my_list.remove(25)
print("After remove:", my_list)

my_list.pop()
print("After pop:", my_list)

print("Index of 30:", my_list.index(30))
print("Count of 10:", my_list.count(10))

my_list.sort()
print("After sort:", my_list)

my_list.reverse()
print("After reverse:", my_list)

my_list.clear()
print("After clear:", my_list)


After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 30, 40, 50, 60, 70, 80]
After pop: [10, 20, 30, 40, 50, 60, 70]
Index of 30: 2
Count of 10: 1
After sort: [10, 20, 30, 40, 50, 60, 70]
After reverse: [70, 60, 50, 40, 30, 20, 10]
After clear: []


In [2]:
student_names = ("Aarav", "Priya", "Rohit")
print("Tuple:", student_names)

try:
    student_names[1] = "Sneha"
except TypeError as e:
    print("Error:", e)

# Explanation:
# Tuples are immutable in Python.
# Once created, their values cannot be changed.
# That is why we get a TypeError when we try to modify an element.


Tuple: ('Aarav', 'Priya', 'Rohit')
Error: 'tuple' object does not support item assignment


In [3]:
#Q3.Set
my_set = {1, 2, 2, 3, 4, 4, 5}
print("Set:", my_set)

# Explanation:
# A set automatically removes duplicate values.
# Even though we added 2 and 4 twice, the set stores only unique values.


Set: {1, 2, 3, 4, 5}


In [4]:
#Q4.Dictionary
person = {
    'name': 'Raju',
    'age': 25,
    'city': 'Mumbai'
}

person['age'] = 26
person['email'] = 'raju@email.com'

print("Final Dictionary:", person)


Final Dictionary: {'name': 'Raju', 'age': 26, 'city': 'Mumbai', 'email': 'raju@email.com'}


In [5]:
#Q5.Voting
age = 20

if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")


You are eligible to vote.


In [6]:
#Q6.Calculator

marks = 86


if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")


Grade: B


In [7]:
#Q7.Positive Negative
number = 5

if number > 0:
    if number % 2 == 0:
        print(number, "is Positive and Even")
    else:
        print(number, "is Positive but Odd")
elif number == 0:
    print("The number is Zero")
else:
    print("The number is Negative")


5 is Positive but Odd


## Section B

In [8]:
#Q8.Scaler

import numpy as np
scalar = np.array(5)
print("Scalar:", scalar)

array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("2D Array:\n", array_2d)


Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


In [9]:
#Q9.Random
import numpy as np

random_array = np.random.randint(0, 100, size=(4, 4))
print("4x4 Random Array:\n", random_array)


4x4 Random Array:
 [[60 55 29 40]
 [87 88 54 71]
 [86 55 59 70]
 [ 2 72 37 58]]


In [10]:
#Q10.2D
import numpy as np
import pandas as pd

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

df = pd.DataFrame(arr, columns=['W', 'R', 'U'])
print(df)


   W  R  U
0  1  2  3
1  4  5  6
2  7  8  9


In [11]:
#Q11.DataFrame
import pandas as pd

data = {
    'Name':   ['Dipak', 'Aakash', 'Mayur', 'Chetan', 'Rohit',
                'Sakshi', 'Nikita', 'Neha', 'Prachi', 'Jagruti'],
    'Age':    [23, 25, 22, 30, 28, 35, 27, 24, 29, 31],
    'City':   ['Mumbai', 'Nashik', 'Pune', 'Jalgaon', 'Amravati',
                'Kolhapur', 'Delhi', 'Nagpur', 'Chennai', 'Kolkata'],
    'Salary': [30000, 45000, None, 50000, 38000,
                60000, None, 42000, 35000, 55000]
}

df = pd.DataFrame(data)

print("--- .info() ---")
print(df.info())

print("\n--- .describe() ---")
print(df.describe())

print("\n--- Name and City columns ---")
print(df[['Name', 'City']])

df = df.drop(columns=['City'])
print("\n--- After dropping City ---")
print(df)

df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
print("\n--- After filling missing Salary with mean ---")
print(df)

df = df.drop_duplicates()
print("\n--- After removing duplicates ---")
print(df)


--- .info() ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

--- .describe() ---
             Age        Salary
count  10.000000      8.000000
mean   27.400000  44375.000000
std     4.033196  10211.163359
min    22.000000  30000.000000
25%    24.250000  37250.000000
50%    27.500000  43500.000000
75%    29.750000  51250.000000
max    35.000000  60000.000000

--- Name and City columns ---
      Name      City
0    Dipak    Mumbai
1   Aakash    Nashik
2    Mayur      Pune
3   Chetan   Jalgaon
4    Rohit  Amravati
5   Sakshi  Kolhapur
6   Nikita     Delhi
7     Neha    Nagpur
8   Prachi   Chennai
9  Jagruti   Kolkata

--- After dropping City --